// export const generateDataSet = (n = 450) => {
//     return new Array(n)
//     //   .fill({ id: '1', title: 'Account Linda Mathew ABCDEFGHIJ102900299800000' })
//       .fill({ id: '1', title: 'ABCDEFGHIJ102900299800000ABCDEFGHIJ102900299800000' })
//       .map((item, i) => ({ ...item, id: i.toString(), title: item.title + i }))
//   }

  export const generateDataSet = () => {
    const data = [
      { id: 1, title: 'Apple' },
      { id: 2, title: 'Banana' },
      { id: 3, title: 'Carrot' },
      { id: 4, title: 'Dog' },
      { id: 5, title: 'Elephant' },
      { id: 6, title: 'Flower' },
      { id: 7, title: 'Guitar' },
      { id: 8, title: 'House' },
      { id: 9, title: 'Ice Cream' },
      { id: 10, title: 'Jungle' },
      { id: 11, title: 'Kite' },
      { id: 12, title: 'Lemon' },
      { id: 13, title: 'Mango' },
      { id: 14, title: 'Ninja' },
      { id: 15, title: 'Orange' },
      { id: 16, title: 'Pineapple' },
      { id: 17, title: 'Quill' },
      { id: 18, title: 'Rainbow' },
      { id: 19, title: 'Sunflower' },
      { id: 20, title: 'Tree' },
      { id: 21, title: 'Umbrella' },
      { id: 22, title: 'Violin' },
      { id: 23, title: 'Watermelon' },
      { id: 24, title: 'Xylophone' },
      { id: 25, title: 'Yacht' },
      { id: 26, title: 'Zebra' },
      { id: 27, title: 'Ant' },
      { id: 28, title: 'Bear' },
      { id: 29, title: 'Cat' },
      { id: 30, title: 'Dolphin' },
      { id: 31, title: 'Wyler' },
      { id: 32, title: 'Flamingo' },
      { id: 33, title: 'Giraffe' },
      { id: 34, title: 'Horse' },
      { id: 35, title: 'Iguana' },
      { id: 36, title: 'Jellyfish' },
      { id: 37, title: 'Kangaroo' },
      { id: 38, title: 'Lion' },
      { id: 39, title: 'Monkey' },
      { id: 40, title: 'Nightingale' },
      { id: 41, title: 'Octopus' },
      { id: 42, title: 'Penguin' },
      { id: 43, title: 'Quokka' },
      { id: 44, title: 'Rabbit' },
      { id: 45, title: 'Squirrel' },
      { id: 46, title: 'Tiger' },
      { id: 47, title: 'Unicorn' },
      { id: 48, title: 'Vulture' },
      { id: 49, title: 'Whale' },
      { id: 50, title: 'X-ray Fish' },
      { id: 51, title: 'Yak' },
      { id: 52, title: 'Zucchini' },
      { id: 53, title: 'Airplane' },
      { id: 54, title: 'Boat' },
      { id: 55, title: 'Car' },
      { id: 56, title: 'Dinosaur' },
      { id: 57, title: 'Soccer' },
      { id: 58, title: 'Firetruck' },
      { id: 59, title: 'Golf Cart' },
      { id: 60, title: 'Helicopter' },
      { id: 61, title: 'Ice Cream Truck' },
      { id: 62, title: 'Jet Ski' },
      { id: 63, title: 'Kite' },
      { id: 64, title: 'Limo' },
      { id: 65, title: 'Motorcycle' },
      { id: 66, title: 'Newspaper' },
      { id: 67, title: 'Owl' },
      { id: 68, title: 'Pizza' },
      { id: 69, title: 'Queen' },
      { id: 70, title: 'Rocket' },
      { id: 71, title: 'Spaceship' },
      { id: 72, title: 'Train' },
      { id: 73, title: 'UFO' },
      { id: 74, title: 'Violin' },
      { id: 75, title: 'Waterfall' },
      { id: 76, title: 'Xylophone' },
      { id: 77, title: 'Yacht' },
      { id: 78, title: 'Zoo' },
      { id: 79, title: 'Art' },
      { id: 80, title: 'Basketball' },
      { id: 81, title: 'Camera' },
      { id: 82, title: 'Dancing' },
      { id: 83, title: 'Education' },
      { id: 84, title: 'Football' },
      { id: 85, title: 'Gardening' },
      { id: 86, title: 'Hiking' },
      { id: 87, title: 'Ice Skating' },
      { id: 88, title: 'Juggling' },
      { id: 89, title: 'Karate' },
      { id: 90, title: 'Lacrosse' },
      { id: 91, title: 'Music' },
      { id: 92, title: 'Nature' },
      { id: 93, title: 'Origami' },
      { id: 94, title: 'Painting' },
      { id: 95, title: 'Quilting' },
      { id: 96, title: 'Reading' },
      { id: 97, title: 'Singing' },
      { id: 98, title: 'Travel' },
      { id: 99, title: 'Underwater Exploration' },
      { id: 100, title: 'Video Games' },
    ];
    
    return data;
  }